/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as JoinWaitingListIndexImport } from './routes/join-waiting-list/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const JoinWaitingListIndexRoute = JoinWaitingListIndexImport.update({
  id: '/join-waiting-list/',
  path: '/join-waiting-list/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/join-waiting-list/': {
      id: '/join-waiting-list/'
      path: '/join-waiting-list'
      fullPath: '/join-waiting-list'
      preLoaderRoute: typeof JoinWaitingListIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join-waiting-list': typeof JoinWaitingListIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join-waiting-list': typeof JoinWaitingListIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/join-waiting-list/': typeof JoinWaitingListIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/join-waiting-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/join-waiting-list'
  id: '__root__' | '/' | '/join-waiting-list/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinWaitingListIndexRoute: typeof JoinWaitingListIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinWaitingListIndexRoute: JoinWaitingListIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/join-waiting-list/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/join-waiting-list/": {
      "filePath": "join-waiting-list/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
